version: "3.1"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passwprd
      MYSQL_DATABASE: gradleappdb
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: test
      MYSQL_USER: test
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
