spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gradleappdb
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      encoding: UTF-8

logging:
  level:
    root: info
  file:
    name: app.log
  logback:
    rollingpolicy:
      max-file-size: 1MB

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
