spring:
  datasource:
    url: jdbc:mysql://localhost/gradleappdb
    username: test
    password: test
  sql:
    init:
      mode: always
      encoding: UTF-8

logging:
  level:
    root: info
  file:
    name: app.log
  logback:
    rollingpolicy:
      max-file-size: 1MB

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true